name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: npm
      - name: install vercel cli
        run: npm install --global vercel@latest
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      # - name: unit tests
      #   run: npm run test
      - name: build app
        run: npm run build
      - name: config vercel cli
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy to vercel
        run: vercel deploy --prebuilt